Blood_e_Merry/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import reverse_lazy
from django.views.generic import RedirectView

# from loginsignup import views
#
# # above import might not work
from Blood_e_Merry import views

urlpatterns = [
    url(r'^$', views.redirect_home, name='redirect_home'),  # actual home page
    url(r'^home/', include('loginsignup.urls')),
    url(r'^admin/', admin.site.urls),
]

loginsignup/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout

from . import views

app_name = 'loginsignup'
urlpatterns = [
    # ex: /home/
    url(r'^$', views.home, name='home'),
    # ex: /home/signup/
    url(r'^signup/$', views.signup, name='signup'),
    # ex: /home/confirmation/
    url(r'^confirmation/$', views.confirmation, name='confirmation'),
    # ex: /home/login/
    url(r'^login/$', login, {'template_name': 'loginsignup/login.html'}, name='login'),
    # ex: /home/profile/
    url(r'^profile/$', views.profile, name='profile'),
    # ex: /home/logout/
    url(r'^logout/$', logout, {'template_name': 'loginsignup/logout.html'}, name='logout'),
    # ex: /home/profile/edit/
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    # ex: /home/change-password/
    url(r'^change-password/$', views.change_password, name='change_password'),

    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
]

loginsignup/models.py
import subprocess
import sys
from datetime import datetime

from django.db.models.signals import post_save
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import logging

logger = logging.getLogger(__name__)

@python_2_unicode_compatible
class Donor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=10, default='')
    city = models.CharField(max_length=30, default='')
    state = models.CharField(max_length=30, default='')
    country = models.CharField(max_length=30, default='')
    reg_date = models.DateTimeField(default=datetime.now, blank=True)
    email_confirmed = models.BooleanField(default=False)
    blood_group = models.CharField(max_length=2, default='')

    def __str__(self):
        return self.user.username

    def was_reg_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.reg_date <= now

    was_reg_recently.admin_order_field = 'reg_date'
    was_reg_recently.boolean = True
    was_reg_recently.short_description = 'Registered recently?'


# create and save donor object, after saving user object
def create_profile(sender, **kwargs):
    if kwargs['created']:
        logger.error('Donor creation trigger!')
        user_profile = Donor.objects.create(user=kwargs['instance'])


'''
signal trigger
Specifying sender limits the receiver
to just post_save signals sent for saves of that particular model.
'''
post_save.connect(create_profile, sender=User)


# spawn subprocess to trigger tweepy
# output of subprocess DOES NOT log to the console.
def tweepy_tester(sender, **kwargs):
    if kwargs['created']:
        logger.error('tweepy trigger-start!')
        p = subprocess.Popen([sys.executable, "/Users/viseshprasad/PycharmProjects/Blood_e_Merry/loginsignup/threadtest.py"],
                             stdout=subprocess.PIPE,
                             stderr=subprocess.STDOUT)
        logger.error('tweepy trigger-over!')


# use post_save to trigger tweepy later
# post_save.connect(tweepy_tester, sender=User)

loginsignup/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, ReadOnlyPasswordHashField
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe

from loginsignup.models import Donor


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True, help_text='Required. Provide a valid email address.', max_length=30)
    phone = forms.CharField(required=True, help_text='Required.', max_length=10)
    city = forms.CharField(required=True, help_text='Required.', max_length=30)
    state = forms.CharField(required=True, help_text='Required.',  max_length=30)
    country = forms.CharField(required=True, help_text='Required.', max_length=30)
    blood_group = forms.CharField(required=True, help_text='Required. Example: B+', max_length=2)

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2',
            'blood_group',
            'phone',
            'city',
            'state',
            'country',
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class EditProfileForm(UserChangeForm):
    password = ReadOnlyPasswordHashField(
        label="",
        help_text=mark_safe(
            "Change the password using "
            "<a href=\"http://127.0.0.1:8000/home/change-password/\"><strong>this form</strong></a>."
        ),
    )

    email = forms.EmailField(required=True, help_text='Required. Provide a valid email address.', max_length=30)
    phone = forms.CharField(required=True, help_text='Required.', max_length=10)
    city = forms.CharField(required=True, help_text='Required.', max_length=30)
    state = forms.CharField(required=True, help_text='Required.',  max_length=30)
    country = forms.CharField(required=True, help_text='Required.', max_length=30)
    blood_group = forms.CharField(required=True, help_text='Required. Example: B+', max_length=2)

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'blood_group',
            'phone',
            'city',
            'state',
            'country',
            'password',
        )
        # exclude = ['username', 'password', 'password1', 'password2']

    # def save(self, commit=True):
    #     user = super(UserChangeForm, self).save(commit=False)
    #     user.first_name = self.cleaned_data['first_name']
    #     user.last_name = self.cleaned_data['last_name']
    #     user.email = self.cleaned_data['email']
    #
    #     if commit:
    #         user.save()
    #
    #     return user

loginsignup/views.py
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
import logging

from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from ipware.ip import get_ip

from loginsignup.forms import RegistrationForm, EditProfileForm
from loginsignup.tokens import account_activation_token

logger = logging.getLogger(__name__)


# Create your views here.

# use generic views

def home(request):
    return render(request, 'loginsignup/index.html', {})


def confirmation(request):
    return render(request, 'loginsignup/confirmation.html', {})


def signup(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)  # takes the post data from request
        if form.is_valid():
            user = form.save()
            user.is_active = False
            user.refresh_from_db()
            user.donor.blood_group = form.cleaned_data.get('blood_group')
            user.donor.phone = form.cleaned_data.get('phone')
            user.donor.city = form.cleaned_data.get('city')
            user.donor.state = form.cleaned_data.get('state')
            user.donor.country = form.cleaned_data.get('country')
            user.save()
            user.donor.save()
            current_site = get_current_site(request)
            subject = 'Activate Your Blood-e-Merry Account'
            message = render_to_string('loginsignup/activation.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message, from_email='visesh@bloodemerry.com')
            # raw_password = form.cleaned_data.get('password1')
            # user = authenticate(username=user.username, password=raw_password)
            # login(request, user)
            return HttpResponseRedirect(reverse('loginsignup:confirmation'))
        else:
            logger.error('Form invalid')
            return render(request, 'loginsignup/signup.html', {'form': form, 'error_message': "Form data invalid!", })
            # username = form.cleaned_data.get('username')
            # raw_password = form.cleaned_data.get('password1')
            # user = authenticate(username=username, password=raw_password)
            # # if user is not None:
            # login(request, user)

    else:
        form = RegistrationForm()
        return render(request, 'loginsignup/signup.html', {'form': form})


def profile(request):
    args = {'user': request.user}
    client_address = get_ip(request)
    logger.error('ip=' + client_address)
    return render(request, 'loginsignup/profile.html', args)


def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)  # takes the post data from request
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.donor.blood_group = form.cleaned_data.get('blood_group')
            user.donor.phone = form.cleaned_data.get('phone')
            user.donor.city = form.cleaned_data.get('city')
            user.donor.state = form.cleaned_data.get('state')
            user.donor.country = form.cleaned_data.get('country')
            user.save()
            user.donor.save()
            return HttpResponseRedirect(reverse('loginsignup:profile'))
        else:
            logger.error('Form invalid')
            return render(request, 'loginsignup/edit_profile.html', {'form': form, 'error_message': "Form data invalid!", })

    else:
        form = EditProfileForm(instance=request.user)
        return render(request, 'loginsignup/edit_profile.html', {'form': form})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.donor.email_confirmed = True
        user.save()
        user.donor.save()
        login(request, user)
        return render(request, 'loginsignup/index.html', {})
    else:
        return render(request, 'loginsignup/account_activation_invalid.html')


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)  # takes the post data from request
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return HttpResponseRedirect(reverse('loginsignup:profile'))
        else:
            logger.error('Form invalid')
            return render(request, 'loginsignup/change_password.html', {'form': form, 'error_message': "Form data invalid!", })

    else:
        form = PasswordChangeForm(user=request.user)
        return render(request, 'loginsignup/change_password.html', {'form': form})

loginsignup/templates/loginsignup/account_activation_invalid.html
{% extends 'loginsignup/base.html' %}

{% block content %}
  <p>The confirmation link was invalid, possibly because it has already been used.</p>
{% endblock %}

loginsignup/templates/loginsignup/activation.html
{% autoescape off %}
Hi {{ user }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'loginsignup:activate' uidb64=uid token=token %}
{% endautoescape %}

loginsignup/templates/loginsignup/base.html
{% load staticfiles %}

<html>
<head>
    <title>{% block title %}Blood-e-Merry{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'loginsignup/styles.css' %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body link="#f8f8ff">
<br>
<div class="container">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Blood-e-Merry</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                {% if user.is_authenticated %}
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'loginsignup:home' %}">Home</a></li>
                        <li><a href="{% url 'loginsignup:profile' %}">Profile</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'loginsignup:logout' %}">Log out</a></li>
                    </ul>
                {% else %}
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'loginsignup:login' %}">Login</a></li>
                        <li><a href="{% url 'loginsignup:signup' %}">Signup</a></li>
                    </ul>
                {% endif %}
            </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
    </nav>
</div>
{% block content %}
    <h1>Base</h1>
{% endblock %}
</body>
<script
        src="https://code.jquery.com/jquery-3.1.1.min.js"
        integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
</html>

loginsignup/templates/loginsignup/change_password.html
{% extends 'loginsignup/base.html' %}


{% block head %}
<title>Change Password</title>
{% endblock %}

{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

loginsignup/templates/loginsignup/confirmation.html
{% extends 'loginsignup/base.html' %}

{% block content %}
<div class="container">
    <h1>You've signed up!</h1>
    <p>
        Signup is complete. A verification email has been sent.
    </p>
</div>
{% endblock %}

loginsignup/templates/loginsignup/edit_profile.html
{% extends 'loginsignup/base.html' %}

{% block title %}Edit Profile{% endblock %}

{% block content %}

    <div class="container">
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
    </div>
    <div id="content">
        <div class="container">
            <h2>Edit Profile</h2>
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
{#                    {% if "password" not in field %}#}
                        <p>
                            {{ field.label_tag }}<br>
                            {{ field }}
                            {% if field.help_text %}
                                <small style="color: ghostwhite">{{ field.help_text }}</small>
                            {% endif %}
                            {% for error in field.errors %}
                                <p style="color: black">{{ error }}</p>
                            {% endfor %}
                        </p>
{#                    {% endif %}#}
                {% endfor %}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

loginsignup/templates/loginsignup/index.html
{% extends 'loginsignup/base.html' %}

{% block content %}
    <div class="container">
        <h1>Welcome!</h1>
        <p>
        <h3>We are Blood-e-Merry.</h3> <h4> A group of coders formed to make a difference ... with the help of a few
        awesome APIs ... and well, StackOverflow ;)</h4><br>

        <h5>How we work:</h5>
        <ul>
            <li>All you have to do is spend a couple minutes with a <a href="{% url 'loginsignup:signup' %}"><strong>signup</strong></a> process.<br></li>
            <li>Once you are signed up, you will start receiving text messages when people ask for blood donors.<strong>
                ( No spam. We promise! ) </strong><br></li>
            <li>We match people's requests from Twitter with donors based on the location information.
                <strong>( So make sure you enter your location right! ) </strong></li>
            <br>
        </ul>
        </p>
    </div>
{% endblock %}

loginsignup/templates/loginsignup/login.html
{% extends 'loginsignup/base.html' %}

{% block content %}
    <div id="content">

        <div class="container">
            <h1>Welcome</h1>
            <p>
                You can log in here!
            </p>
            <h2>Login</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
    </div>
{% endblock %}

loginsignup/templates/loginsignup/logout.html
{% extends 'loginsignup/base.html' %}

{% block content %}
<div class="container">
    <h1>Logged out</h1>
    <p>
        You have logged out!
    </p>
</div>
{% endblock %}

loginsignup/templates/loginsignup/profile.html
{% extends 'loginsignup/base.html' %}

{% block content %}
    <div id="content">
        <div class="container">
            <h1>Profile</h1><br>
            <div class=table-responsive>
                <form action="{% url 'loginsignup:edit_profile' %}">
                    <table class="table table-condensed table-hover table-nonfluid">
                        <tbody>
                        <tr>
                            <th scope=row>Username:</th>
                            <td>{{ user }}</td>
                        </tr>
                        <tr>
                            <th scope=row>First name:</th>
                            <td>{{ user.first_name }}</td>
                        </tr>
                        <tr>
                            <th scope=row>Last name:</th>
                            <td>{{ user.last_name }}</td>
                        </tr>
                        <tr>
                            <th scope=row>Email:</th>
                            <td>{{ user.email }}</td>
                        </tr>
                        <tr>
                            <th scope=row>Blood Group:</th>
                            <td>{{ user.donor.blood_group }}</td>
                        </tr>
                        <tr>
                            <th scope=row>Phone:</th>
                            <td>{{ user.donor.phone }}</td>
                        </tr>
                        <tr>
                            <th scope=row>City:</th>
                            <td>{{ user.donor.city }}</td>
                        </tr>
                        <tr>
                            <th scope=row>State:</th>
                            <td>{{ user.donor.state }}</td>
                        </tr>
                        <tr>
                            <th scope=row>Country:</th>
                            <td>{{ user.donor.country }}</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                        </tr>

                        </tbody>
                    </table>
                                <button type="submit" class="btn btn-primary">Edit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

loginsignup/templates/loginsignup/signup.html
{% extends 'loginsignup/base.html' %}

{% block title %}Signup{% endblock %}

{% block content %}

    <div class="container">
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
    </div>
    <div id="content">
    <div class="container">
        <h2>Sign up</h2>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <p>
                    {{ field.label_tag }}<br>
                    {{ field }}
                    {% if field.help_text %}
                        <small style="color: ghostwhite">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                        <p style="color: black">{{ error }}</p>
                    {% endfor %}
                </p>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Sign up</button>
        </form>
    </div>
</div>
{% endblock %}